/*
 * generated by Xtext
 */
package algorithmMaker.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class InputUiModule extends algorithmMaker.ui.AbstractInputUiModule {
	public InputUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
