/**
 * generated by Xtext
 */
package algorithmMaker.ui.contentassist;

import algorithmMaker.ui.contentassist.AbstractInputProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class InputProposalProvider extends AbstractInputProposalProvider {
}
