/*
* generated by Xtext
*/
package algorithmMaker;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class InputStandaloneSetup extends InputStandaloneSetupGenerated{

	public static void doSetup() {
		new InputStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

