/*
 * generated by Xtext
 */
package algorithmMaker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InputRuntimeModule extends algorithmMaker.AbstractInputRuntimeModule {

}
