/*
 * generated by Xtext
 */
package algorithmMaker.language.property;

import algorithmMaker.AbstractInputRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PropertyRuntimeModule extends AbstractInputRuntimeModule {
	@Override
	public Class<? extends org.eclipse.xtext.parser.IParser> bindIParser() {
		return PropertyParser.class;
	}
}
