/*
 * generated by Xtext
 */
package algorithmMaker.validation

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class InputValidator extends AbstractInputValidator {
	
	//TODO:Validation: check for legal variable names
	//TODO:Validation: prevent variables with same name as something in scope (mostly for quantifiers?)
	//TODO:Validation: do typechecking
	//TODO:Validation: warn if desired output has nothing to do with input

//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//	}
}
