/*
 * generated by Xtext
 */
package algorithmMaker.validation

/**
 * Custom validation rules. 
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class InputValidator extends AbstractInputValidator {
}
