/**
 * generated by Xtext
 */
package algorithmMaker.validation;

import algorithmMaker.validation.AbstractInputValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class InputValidator extends AbstractInputValidator {
}
